backend:
  name: git-gateway
  branch: master

media_folder_relative: true

collections:
    - name: "programming"
      label: "Programming"
      folder: "content/programming"
      create: true
      fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Exhibition Start", name: "exhibition_start", widget: "string" }
        - { label: "Exhibition End", name: "exhibition_end", widget: "string" }
        - { label: "Artists", name: "artists", widget: "string" }
        - { label: "Curators", name: "curators", widget: "string" }
        - { label: "Body", name: "body", widget: "markdown" }
